services: 
  mysql-products-db:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./sql_dump/products_db_product_tags.sql:/docker-entrypoint-initdb.d/products_db_product_tags.sql
      - ./sql_dump/products_db_products.sql:/docker-entrypoint-initdb.d/products_db_products.sql
      - ./sql_dump/products_db_tags.sql:/docker-entrypoint-initdb.d/products_db_tags.sql
  
  spring-boot-products-manager:
    depends_on:
      - mysql-products-db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-products-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - ~/.gradle:/root/.gradle
    stdin_open: true
  
  angular-ui:
    build: ../ui/
    ports:
      - '4200:4200'
    volumes:
      - ../tomer-fried-products-ui-service/:/app

volumes:
  db:
